stages:
  - build
  - test

minimum:
  image: $TESTING_DOCKER_IMAGE
  stage: build
  script:
    - curl -OLs ${TESTING_BASE_URL}/${TESTING_SECRET}/CIFileExistenceCheck
    - curl -OLs ${TESTING_BASE_URL}/${TESTING_SECRET}/massPullOptions.cfg
    - python3 CIFileExistenceCheck massPullOptions.cfg
  artifacts:
    expire_in: 1 week

