/*
 * File:   Negotiation.c
 * Author: Luca Altaffer taltaffe@ucsc.edu
 *
 * Created on March 10, 2022, 9:46 AM
 */

#include <stdint.h>
#include "xc.h"
#include "BOARD.h"
#include "Negotiation.h"

#define BIT_COUNT_LIMIT 16

/**
 * This function implements a one-way hash.  It maps its input, A, 
 * into an image, #a, in a way that is hard to reverse, but easy 
 * to reproduce.
 * @param secret        //A number that a challenger commits to
 * @return hash         //the hashed value of the secret commitment.
 *
 * This function implements the "Beef Hash," a variant of a Rabin hash.
 * The result is ((the square of the input) modulo the constant key 0xBEEF).
 * So, for example, 
 * 
 * NegotiationHash(3) == 9
 * NegotiationHash(12345) == 43182
 */
NegotiationData NegotiationHash(NegotiationData secret){
     NegotiationData squared = secret * secret;
    return squared % PUBLIC_KEY;
}

/**
 * Detect cheating.  An accepting agent will receive both a commitment hash
 * and a secret number from the challenging agent.  This function
 * verifies that the secret and the commitment hash agree, hopefully
 * detecting cheating by the challenging agent.
 *
 * @param secret        //the previously secret number that the challenging agent has revealed
 * @param commitment    //the hash of the secret number
 * @return TRUE if the commitment validates the revealed secret, FALSE otherwise
 */
int NegotiationVerify(NegotiationData secret, NegotiationData commitment){
    NegotiationData checkSecret = NegotiationHash(secret);
    
    if (checkSecret != commitment){ 
        // If our hash calculation does not match the challenger's
        return FALSE;
    }
    
    else{
        return TRUE; 
        // Our hash calculation matches the challenger's
    }
}

/**
 * The coin-flip protocol uses random numbers generated by both
 * agents to determine the outcome of the coin flip.
 *
 * The parity of a bitstring is 1 if there are an odd number of one bits,
 *   and 0 otherwise.
 * So, for example, the number 0b01101011 has 5 ones.  If the parity of
 * A XOR B is 1, then the outcome is HEADS.  Otherwise, the outcome is TAILS.
 */
NegotiationOutcome NegotiateCoinFlip(NegotiationData A, NegotiationData B){
    NegotiationData xorBits = A ^ B;
    int numBits = 0;  // Store how many bits are 1's in our xor bitstring
    int count = 0;    // Store which bit we are looking at
    int whichBit = 0; // Hold the correct value to & our xor bitstring with 
    
    for (count; count < BIT_COUNT_LIMIT; count++){
        whichBit = 1 << count; // Shift the 1 bit over to the proper location
                               // to represent 1, 2, 4, 8, etc.
        if (xorBits & whichBit){ // Check if our xor bitstring has a 1 in that bit location
            numBits++; // If it does add to our counter
        }
    }
    
    if (numBits % 2){ 
        return HEADS;
    }
    
    else{
        return TAILS;
    }
}


/**
 * Extra credit: 
 * Use either or both of these two functions if you want to generate a "cheating" agent.  
 *
 * To get extra credit, define these functions 
 * and use these functions in agent.c to generate A and/or B
 * 
 * Your agent only needs to be able to cheat at one role for extra credit.  They must result in 
 * your agent going first more than 75% of the time in that role when
 * competing against a fair agent (that is, an agent that uses purely random A and B).
 *
 * You must state that you did this at the top of your README, and describe your 
 * strategy thoroughly.
 */
NegotiationData NegotiateGenerateBGivenHash(NegotiationData hash_a){
    
}
NegotiationData NegotiateGenerateAGivenB(NegotiationData B){
    
}
